### ISSUE TITLE
Electrum-VTC-TOR 2.9.3.3 - Transaction with 139 confirmations (and counting) not verified

### ISSUE THREAD

**Issue by titan49er** [vertcoin/electrum-vtc#63] opened 2017-12-21 08:19 UTC
My Electrum-VTC-TOR 2.9.3.3 on macOS 10.12.6 is showing my transactions but they're "Not Verified" even though the blockchain explorer shows 139 confirmations and counting. The previous ticket for this problem was closed.

How do I fix this?

**Comment by metalicjames** [comment] 2017-12-28 03:04
Duplicate of #58

**Closed as completed by metalicjames** 2017-12-28 03:04 UTC
Labels: duplicate
