### ISSUE TITLE
Electrum wallet not connected

### ISSUE THREAD

**Issue by urbanet74** [vertcoin/electrum-vtc#55] opened 2017-12-09 18:06 UTC
Hi, I've got VTC electrum 2.9.3.1 wallet version and tried anything.
Add server manually, uncheck USE SSL but nothing works and my wallet is offline.
What should I doing now? Please help me

**Comment by rbish** [comment] 2017-12-09 19:55
I have VTC electrum 2.9.3.3 wallet but "not connected" so can't send tokens, any idea on why won't connect?  thank you

**Comment by gitinthetrunk** [comment] 2017-12-09 21:49
having the same problem on 2933 on a Mac

**Comment by MNKanout** [comment] 2017-12-09 21:59
Same here.
Windows 10 64bit. Version 2.9.3.3
Not connected.

**Comment by mtompkins** [comment] 2017-12-09 22:24
Same V2.9.3.3 Linux

**Comment by jinkobah** [comment] 2017-12-10 00:02
Same. v2.9.3.3 on Win10 64bit.

Edit: I unchecked SSL and selected server manually, but this did not work at first. However, I went back to the Network->Overview after about 10min and servers were available. Selecting a server worked and my Rx went through.

**Comment by mtompkins** [comment] 2017-12-10 13:01
Things are connecting this AM. Seems it may just have been load on the backend.

**Comment by metalicjames** [comment] 2017-12-28 20:23
Duplicate of #52

**Closed as completed by metalicjames** 2017-12-28 20:23 UTC
