### ISSUE TITLE
argument 1:<class'OverflowError'>:int too long to convert

### ISSUE THREAD

**Issue by odivinewraitho** [vertcoin/electrum-vtc#100] opened 2018-08-20 21:57 UTC
I cannot send vtc.

When I am attempting to send vtc, I can given this error. It doesn't appear to be the amount that I send, as I have tried many amounts. 

Would anyone happen to have any ideas.

**Comment by metalicjames** [comment] 2018-08-20 21:59
Duplicate of #99

**Closed as completed by metalicjames** 2018-08-20 21:59 UTC
