### ISSUE TITLE
Cannot connect without Disabling SSL 

### ISSUE THREAD

**Issue by FuFelix** [vertcoin/electrum-vtc#54] opened 2017-12-09 10:13 UTC
If I disable SSL I can connect to a list of Default Servers, however, I did not need to do this previously, 

Do not want to connect with SSL disabled.

**Comment by metalicjames** [comment] 2017-12-28 03:08
Is this still a problem for you?

**Comment by metalicjames** [comment] 2017-12-28 20:22
Duplicate of #52

**Closed as completed by metalicjames** 2017-12-28 20:22 UTC
