### ISSUE TITLE
Status : Not Connected

### ISSUE THREAD

**Issue by Conqu3rer** [vertcoin/electrum-vtc#39] opened 2017-10-27 12:16 UTC
Electrum Windows Wallet is showing "Not Connected" all the time. Wallet is not syncing as well.

**Comment by metalicjames** [comment] 2017-10-27 19:55
Is Windows firewall blocking connections? You may need to add a firewall exception.

**Comment by Bodierobins** [comment] 2017-10-28 18:21
Tried many times to navigate Bitdefender to enable the network connection for the wallet.  Still no luck. It continues to be unconnected.

**Comment by Conqu3rer** [comment] 2017-10-28 18:33
Already tried everything, enabled/disabled firewall. Nothing works.

**Comment by Conqu3rer** [comment] 2017-10-31 02:00
Still "Not connected"

**Comment by jhabdas** [comment] 2017-10-31 10:09
4 days and no upvotes. Is this really an issue?

**Comment by samnz001** [comment] 2017-11-07 05:11
Looks like I have the same problem, tried it on a Mac air and iMac, same problem, not connected!

**Comment by swieny** [comment] 2017-12-07 12:40
I get it connected by disabling SSL. 
Bitcoin Electrum works fine with SSL on the same machine (Debian 9).

**Comment by doublea** [comment] 2017-12-08 03:03
Same issue. Can confirm disabling SSL works.

**Comment by Panzzy** [comment] 2017-12-10 06:12
Same problem here. Something wrong with the servers?

**Comment by gitinthetrunk** [comment] 2017-12-10 14:47
Disabling SSL does not work for me on a Mac

**Comment by jopacicdev** [comment] 2017-12-27 07:27
I had same issue on Win10, and after disabling SSL (Tools > Network > Proxy > Uncheck 'Use SSL') it connected.

**Comment by metalicjames** [comment] 2017-12-28 20:24
Duplicate of #52

**Closed as completed by metalicjames** 2017-12-28 20:24 UTC
