### ISSUE TITLE
Electrum Portable wallet - 3.2.2 - <class 'OverflowError'>: int too long to convert

### ISSUE THREAD

**Issue by silverdelange** [vertcoin/electrum-vtc#103] opened 2018-09-10 08:16 UTC
Hi.

I am using Electrum Portable wallet and when I want to send coins to a cold address it gives me the following error;
argument 1: <class 'OverflowError'>: int too long to convert

Windows 10 64 bit.

Any advice will be appreciated.

Thank you.

**Comment by metalicjames** [comment] 2018-10-04 23:05
Closing as duplicate of #99

**Closed as completed by metalicjames** 2018-10-04 23:05 UTC
