### ISSUE TITLE
Electrum not connected

### ISSUE THREAD

**Issue by hosseinmor1** [vertcoin/electrum-vtc#53] opened 2017-12-07 18:56 UTC
for some reasons, Electrum is not getting connected.
removed the software and reinstalled, did not work. used different computers and different networks.
any idea?

**Comment by stefonarch** [comment] 2017-12-08 09:51
Duplicate of https://github.com/vertcoin/electrum-vtc/issues/52
Selecting manually and   proxy → disable SSL solves, but disabling ssl not looks like a very cool thing to do...

**Comment by hosseinmor1** [comment] 2017-12-08 14:21
Thanks

**Comment by gitinthetrunk** [comment] 2017-12-10 14:45
Disabling does nothing for me on Mac

**Comment by stefonarch** [comment] 2017-12-10 15:40
Disabling "select server automatically" and uncheck ssl you have to choose manually (right-click) one of the servers, the only one working was one from coinomi.

But frankly said I don't like that at all, it is a private company and was already in trouble for not using ssl for communications.

I saw that vertcoin electrum tor wallet connects well, still manually selecting one of the servers but with SSL checked.

**Comment by metalicjames** [comment] 2017-12-28 20:22
Duplicate of #52

**Closed as completed by metalicjames** 2017-12-28 20:22 UTC
