### ISSUE TITLE
Synching bug

### ISSUE THREAD

**Issue by tamlin-mike** [vertcoin/electrum-vtc#58] opened 2017-12-14 05:45 UTC
Windows.
Due to the time required to do a full synch, I shut down the client by normal means. At that point it was a little over halfways synchronized.

On next startup, it connected to some servers, pulled some data, churned CPU a bit, and removed one server from the (auto-discovered) list. This it repeated until the list was empty, then it repopulated the list and started over. Never did the local height budge (it was stuck at ~466k), nor did it write anything at all to disk.

This was clearly an error condition, but I could not find neither (required) debug logs nor options to turn on debug logging to see exactly what had failed (this could be considered a feature request).

My suspicion is `blockchain_headers` might have been left in an unexpected state, that is not handled when synching should resume. I currently consider this a data-loss bug (i.e. major).

I have saved the `blockchain_headers` file (a little over 35MB), in case it could help research the issue.

**Comment by tamlin-mike** [comment] 2017-12-14 06:20
Follow-up: It seems the problem isn't what I originally thought. On a re-run after removing the old headers file, it still stops. Exactly the same file size, and at the very same block.

Local height: 467711
Remotes height: 841292 and counting

**Comment by metalicjames** [comment] 2017-12-28 03:11
Fixed in e3f90acd9b65941b9cc91c015996aa57a3d8d4aa

**Closed as completed by metalicjames** 2017-12-28 03:11 UTC
Labels: bug

**Comment by tamlin-mike** [comment] 2017-12-30 18:33
@metalicjames While it works (or at least seems to work - it fixed the immediate problem), I'd like an elaboration on what messed it up, and also a comment in the source code what problem it's working around. Especially since it's targeting a specific block. Without comment, it looks like an unwarranted hack.

**Comment by metalicjames** [comment] 2017-12-30 19:21
I honestly don't know, it only affects that block. I'm guessing it's a bug in Python at this point, the implementation is the same as the C++/Go which does not exhibit this issue. If you have a more enlightened view, please share it. 

Also, we intend to replace Electrum-VTC with our own bespoke wallet soon anyway. Spending valuable time finding and working around the root cause is simply not worth it.

**Comment by tamlin-mike** [comment] 2017-12-30 20:06
The only thing I have been able to imagine is (dec)467711 = 0x722FF, i.e. ending in 0xff. IFF that's (in error) considered an error somewhere, or if there's even a bug in python itself... I haven't got a clue.

As the specific block targeted in the workaround is not ending in 0xff... IDK. Almost like a mystery.
I'd still like to get to the bottom of it, since it reeks of danger.

> Also, we intend to replace Electrum-VTC with our own bespoke wallet soon anyway.

Gotcha. It's just the bug-hunter in me wanting to get to the root of the problem.

Happy hacking!
