### ISSUE TITLE
Unable to connect to electrum-vtc

### ISSUE THREAD

**Issue by kumarbellamkonda** [vertcoin/electrum-vtc#56] opened 2017-12-10 15:16 UTC
Hi,
I am unable to connect to electrum vtc even though  i have did unselected ssl,server and tried to load each avilable server manually.

**Comment by jasonjalves** [comment] 2017-12-10 18:11
I am having the same issue.  I have already updated my firewall settings to allow permission for electrum

**Comment by metalicjames** [comment] 2017-12-28 03:06
Is this still an issue for you? There are at least three servers up and available via SSL at present.

**Comment by metalicjames** [comment] 2017-12-28 20:23
Duplicate of #52

**Closed as completed by metalicjames** 2017-12-28 20:23 UTC
