### ISSUE TITLE
Vertcoin from wallet error

### ISSUE THREAD

**Issue by joedully** [vertcoin/electrum-vtc#102] opened 2018-08-26 08:38 UTC
Not able to send Vertcoin from wallet. When entering password on Send,  electrum argument1: <class 'Overflow'>: int too long to convert. I see that this was fixed in electrum-dash 3.2.2.1. electrum-vert still has the problem.

**Comment by metalicjames** [comment] 2018-10-04 23:05
Duplicate of #99

**Closed as completed by metalicjames** 2018-10-04 23:05 UTC
