### ISSUE TITLE
Electrum vtc 2.9.3.3 stays indefinite time on "unconfirmed"

### ISSUE THREAD

**Issue by VenciVT** [vertcoin/electrum-vtc#41] opened 2017-10-27 16:53 UTC
After initiating transaction of vtc to confirmed address the status doesn't seem to change for 24 hours already.

Restarting the pc and the wallet doesn't help.

Please advise what to do?

Best regards,
Venci

**Comment by goodc0re** [comment] 2017-10-27 17:48
Find a solution in issue #33:
https://github.com/vertcoin/electrum-vtc/issues/33

**Comment by metalicjames** [comment] 2017-10-27 19:51
Duplicate of #33

**Closed as completed by metalicjames** 2017-10-27 19:51 UTC
Labels: duplicate
